workers:
  workers.radarr:
    enabled: true
    schedule:
      type: interval
      interval: 3
    max_runtime: null
    max_instances: 1
  workers.sonarr:
    enabled: true
    schedule:
      type: interval
      interval: 3
    max_runtime: null
    max_instances: 1
  workers.spot_to_mediaserver:
    enabled: true
    schedule:
      type: interval
      interval: 180
    max_runtime: null
    max_instances: 1
  workers.playlist_to_music_video:
    enabled: true
    schedule:
      type: interval
      interval: 180
    max_runtime: null
    max_instances: 1
