name: Build and publish docker image

on:
  push:
    branches:
    - "develop"

jobs:
  build-and-publish-latest:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2.5.0

    - name: Build and publish "develop" Docker image
      uses: VaultVulp/gp-docker-action@1.5.2
      with:
        github-token: ${{ secrets.GHCR_PAT }}
        image-name: develop
